[package]
name = "orbits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
circular-queue = "0.2.6"
num = "0.4.0"
raylib = { version = "3.7" }
